name: app
version: 0.1.0.0
dependencies:
  - base
  - containers
  - monad-loops
  - ilist
  - split
  - extra
  - conduit
  - random
  - megaparsec
  - parser-combinators
  - mtl
executables:
  app:
    source-dirs: src
    main: Main.hs
