name: app
version: 0.1.0.0
dependencies:
  - base
  - containers
  - monad-loops
  - ilist
  - megaparsec
  - array
  - linear
  - safe
  - extra
  - transformers
  - microlens-platform
  - errors
executables:
  app:
    source-dirs: src
    main: Main.hs
